__author__ = 'susperius'

CSS_STYLES = [['align-content', 'stretch', 'center', 'flex-start', 'flex-end', 'space-between', 'space-around'],
                  ['align-items', 'stretch', 'center', 'flex-start', 'flex-end', 'space-between', 'space-around'],
                  ['align-self', 'stretch', 'center', 'flex-start', 'flex-end', 'space-between', 'space-around'],
                  ['background-attachment', 'fixed', 'scroll', 'local', 'initial', 'inherit'],
                  ['background-color', '#b0c4de', 'none', 'inherit', '#ff6600'],
                  ['background-image', 'http://127.0.0.1:8080/pic.jpg', 'none', 'inherit'],
                  ['background-position', 'size', '50% 50%', '10 10', 'left top', 'right top' 'center top',
                   'left center', 'right center', 'left bottom', 'right bottom', 'center center', 'center bottom',
                   'inherit'],
                  ['background-repeat', 'repeat', 'repeat-x', 'repeat-y', 'no-repeat', 'inherit'],
                  ['background-clip', 'border-box', 'padding-box', 'content-box', 'inherit'],
                  ['background-origin', 'border-box', 'padding-box', 'content-box', 'inherit'],
                  ['background-size', 'auto', '10px 50px', '50%', '100px', 'inherit', 'cover', 'contain'],
                  ['border', 'solid', 'double', 'groove', 'dotted', 'dashed', 'inset', 'outset', 'ridge', 'hidden',
                   'four-sides', '5px'],
                  ['border-bottom', '5px', '#b0c4de', 'thick', '#ff6600'],
                  ['border-bottom-color', '#b0c4de', '#ff6600'],
                  ['border-bottom-style', 'solid', 'double', 'groove', 'dotted', 'dashed', 'inset', 'outset', 'ridge',
                   'hidden'],
                  ['border-bottom-width', '5px', 'thick', 'thin', 'medium'],
                  ['border-color', '#b0c4de', '#ff6600'],
                  ['border-left', '10px', '#ff0000', 'thin', 'thick', 'medium'],
                  ['border-left-color', '#ff0000', '#ff6600'],
                  ['border-left-style', 'solid', 'double', 'groove', 'dotted', 'dashed', 'inset', 'outset', 'ridge',
                   'hidden'],
                  ['border-left-width', '10px', 'thin'],
                  ['border-right', '5px', '#b0c4de', 'thin', 'medium', 'thick'],
                  ['border-right-color', '#b0c4de', '#ff6600'],
                  ['border-right-style', 'solid', 'double', 'groove', 'dotted', 'dashed', 'inset', 'outset', 'ridge',
                   'hidden'],
                  ['border-right-width', '5px', 'thin', 'medium', 'thick'],
                  ['border-style', 'solid', 'double', 'groove', 'dotted', 'dashed', 'inset', 'outset', 'ridge',
                   'hidden', 'four-sides', 'thick'],
                  ['border-top', '5px', '#b0c4de', 'thick', 'thin', 'medium'],
                  ['border-top-color', '#b0c4de', '#ff6600'],
                  ['border-top-style', 'solid', 'double', 'groove', 'dotted', 'dashed', 'inset', 'outset', 'ridge',
                   'hidden'],
                  ['border-top-width', '5px', 'thick'],
                  ['border-width', '5px', 'thick'],
                  ['box-shadow', 'none', 'inherit', '20px 20px 50px 20px pink', '10px 10px black',
                   '10px 10px 50px 20px pink inset', '50px 50px 5px orange', '-20px -20px -50px -20px pink',
                   '10px -10px black', '10px -10px 50px -20px pink inset', '-50px -50px 5px orange'],
                  ['bottom', 'auto', '10px', '-10px', '50%', 'inherit'],
                  ['clear', 'left', 'right', 'both'],
                  ['clip', 'auto', 'rect(0px, 25px, 100px, 0px)', 'rect(20px, 20px, 20px, 20px)'],
                  ['color', '#b0c4de', '#ff6600'],
                  ['direction', 'rtl', 'ltr'],
                  ['display', 'block', 'inline', 'flex', 'run-in', 'list-item', 'table', 'table-caption'],
                  ['float', 'left', 'right'],
                  ['font-family', 'Georgia', 'Palatino Linotype', 'Book Antiqua', 'Arial', 'Helvetica'],
                  ['font-size', '100%', '10px', 'small', 'inherit'],
                  ['font-style', 'italic', 'oblique', 'normal'],
                  ['font-variant', 'small-caps'],
                  ['font-weight', 'bold', '900'],
                  ['height', '100px', 'auto'],
                  ['hanging-punctuation', 'first', 'none', 'last', 'allow-end', 'force-end'],
                  ['justify-content', 'flex-start', 'flex-end', 'center', 'space-between', 'space-around'],
                  ['letter-spacing', '2px'],
                  ['line-height', '2', '90%'],
                  ['list-style', 'circle', 'square', 'disc', 'upper-alpha', 'lower-alpha', 'upper-roman', 'lower-roman',
                   'decimal', 'inside', 'outside', 'none'],
                  ['list-style-image', 'file:///c:/pyfuzz/fuzzing/background.jpg'],
                  ['list-style-position', 'inside', 'outside'],
                  ['list-style-type', 'circle', 'square', 'disc', 'upper-alpha', 'lower-alpha', 'upper-roman',
                   'lower-roman', 'decimal'],
                  ['margin', '5px', '10%', 'auto'],
                  ['margin-bottom', '2px', '30%', 'auto'],
                  ['margin-left', '5px', '50%', 'auto'],
                  ['margin-right', '5px', '50%', 'auto'],
                  ['margin-top', '10px', '60%', 'auto'],
                  ['overflow', 'visible', 'hidden', 'scroll', 'auto', 'inherit'],
                  ['overflow-y', 'visible', 'hidden', 'scroll', 'auto', 'inherit'],
                  ['overflow-x', 'visible', 'hidden', 'scroll', 'auto', 'inherit'],
                  ['padding', '5px', '100%', 'four-sides'],
                  ['padding-bottom', '10px', '100%'],
                  ['padding-left', '5px', '40%'],
                  ['padding-right', '6px', '100%'],
                  ['padding-top', '10px', '40%'],
                  ['position', 'absolute', 'relative', '100%', '100px'],
                  ['text-align', 'right', 'center', 'left', 'justify'],
                  ['text-decoration', 'line-through', 'overline', 'underline', 'none'],
                  # ['text-decoration-color', '#b0c4de', '#ff6600'],
                  # ['text-decoration-style', 'solid', 'double', 'dotted', 'dashed', 'wavy'],
                  ['text-indent', '5px', '5%'],
                  ['text-justify', 'inter-word', 'inter-ideograph', 'inter-cluster', 'distribute', 'kashida', 'trim'],
                  ['text-transform', 'capitalize', 'lowercase', 'uppercase'],
                  ['vertical-align', 'vertical-values'],
                  ['white-space', 'nowrap'],
                  ['width', '100pz', '100%', 'auto'],
                  ['word-spacing', '2px', '10px'],
                  ['z-index', '1']]