import reducing.browser_reducer as br

red = br.BrowserTestcaseReducer("html")

red.set_case("./", "test.html")

red.reduce()
red.crashed(True)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(True)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(True)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(True)
red.reduce()
red.crashed(True)
red.reduce()
red.crashed(True)
red.reduce()
red.crashed(True)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(True)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)
red.reduce()
red.crashed(False)

html_file = red.reduce()


with open("red.html", 'wb+') as fd:
    fd.write(html_file)
